version: "3.9"
services:
  web:
     build:
      context: ./
     ports:
      - 5000:5000
  redis:
    image: "redis:alpine"

  postgres:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mesha
    ports:
    - 5432:5432
    logging:
      options:
        max-size: 10m
        max-file: 3
   


networks:
  backend:
     driver: bridge
