select_all = "SELECT * FROM userss"
login_query2= "SELECT * FROM userss WHERE email = "
login_query = "SELECT * FROM userss WHERE id = "
is_admin = "SELECT * FROM userss WHERE email = "
select_ressources_id = "SELECT * FROM ressources WHERE id = "
select_all_ressources = "SELECT * FROM ressources"
createnorm_user = "insert into userss (email, pwd, role) VALUES (%s, %s, %s)"
promote_user_query = "UPDATE userss SET email= %s, password= %s, role= %s WHERE id = %s"
delete_query = "delete from userss where id = "
delete_ressource_query = "delete from ressources where id = "
create_ressource_query = "insert into ressources ( produto, descricao, quantidade) VALUES ( %s, %s, %s)"
update_ressource_query = "UPDATE ressources SET produto= %s, descricao= %s, quantidade= %s WHERE id = %s"
alocate_ressource_query = "UPDATE ressources SET alocated_at = %s where id = %s"